let a, b;
a = 3; b = 7;
resultado = a*b;
document.write('Variable a contiene ${a}');
document.write('</br>');
document.write('variable b contiene ${b}');
document.write('</br>');
document.write('El producto de a por b es ${result}');
document.write('</br>');
document.write("Los puntos de interrupcion son fundamentales para programar");